apiVersion: gcp.platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  name: emerging-tech-postgres
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parameters:
    engine: postgres
    engineVersion: "13"
    region: europe-central2
    storageGB: 10
    passwordSecretRef:
      namespace: default
      name: psqlsecret
      key: password
    networkRef:
      id: emerging-tech-network
    providerConfigName: emerging-tech-provider
  writeConnectionSecretToRef:
    name: emerging-tech-postgres-conn
