apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-gcp-database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/upbound/configuration-gcp-database:v0.5.0
