apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-demo-backend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  package: xpkg.upbound.io/judasz/configuration-demo-backend:v0.2.0-1.ga250711
